services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: unless-stopped
    env_file: .env
    volumes:
      - ../mongo_data/db:/data/db
      - ../mongo_data/config:/data/configdb
    command: ["mongod", "--bind_ip_all"]

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: unless-stopped
    env_file: .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_INITDB_ROOT_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  omniboard:
    image: vivekratnavel/omniboard:latest
    command:
      - "--mu"
      - "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_DATABASE}?authSource=admin"
    ports:
      - 9000:9000
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo